Modificación en paleta de colores
Luandrada/DEV006-burger-queen-api-client pull request #22
Opened 2023-09-26 20:57 UTC by Luandrada

Modificación en paleta de colores para maejorar la accesibilidad

![image](https://github.com/Luandrada/DEV006-burger-queen-api-client/assets/66980189/dabc256e-140d-42d3-bfb0-ffb0a2bda98f)

2023-09-28 15:11 UTC, kvnlab commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.scss
> +            color: rgb(182, 27, 27);
Tenemos variables para el color, lo que me parece bien, pero por qué no las usas acá? :)

2023-09-28 17:54 UTC, Freihart512 requested changes

2023-09-28 17:54 UTC, Freihart512 commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.html
> +            <button type="submit" id="btn-entrar" class="btn-ppal">Ingresar</button>
🤔 veo que usas en mas lados esta clase, pero no me queda claro porque tal vez podrias darle un nombre mas descriptivo

2023-09-28 17:54 UTC, Freihart512 commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.scss
> +            color: rgb(182, 27, 27);
+1

2023-10-02 15:44 UTC, Luandrada commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.html
> +            <button type="submit" id="btn-entrar" class="btn-ppal">Ingresar</button>
btn-ppal hace referencia a Botón Principal , la uso en los lugares donde quiero que tenga los estilos de un boton principal, este estilo está en el css principal. 

botonPrincipal te suena mejor ?

2023-10-02 16:41 UTC, Freihart512 commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.html
> +            <button type="submit" id="btn-entrar" class="btn-ppal">Ingresar</button>
todo el codigo siempre deberia estar en inlgles por lo que primary-button  creo que seria mejor opcion 

https://stackoverflow.com/questions/7927193/css-class-naming-convention

2023-10-03 13:54 UTC, Luandrada commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.html
> +            <button type="submit" id="btn-entrar" class="btn-ppal">Ingresar</button>
muy buena observación! ya lo apliqué en otras clases también que tenía en español, gracias

2023-10-05 22:34 UTC, Freihart512 requested changes

2023-10-05 22:34 UTC, Freihart512 commented on BurgerQueen/src/app/features/waitress/components/menu/menu.component.scss
> +    color: grey;
si bien entiendo que no siempre vamos a usar variables no se si usar el nombre del color es lo mas adecuado en vez de usar hexadecimal o rgb supongo que con que decidamos cual sera nuestro estandar basta 

con eso mente el nombre no creo que sea la mejor opcion 😅  no se que diga @kvnlab

2023-10-05 22:34 UTC, Freihart512 commented on BurgerQueen/src/app/features/waitress/components/menu/menu.component.scss
> +    color: grey;
en otros lados veo que usamos RGB

2023-10-05 22:34 UTC, Freihart512 commented on BurgerQueen/src/app/features/waitress/components/product-card/product-card.component.scss
>  }
salto de linea

2023-10-05 22:34 UTC, Freihart512 commented on BurgerQueen/src/variables.scss
> +/**************************************/
salto de liena

2023-10-09 15:03 UTC, Freihart512 commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.scss
>              display: block;
Mmm, estoy seguro de haber puesto este comenatrio en otro lado pero no logro verlo pero en fin 

me hace ruido el `display: block`

de entrada porque error text me habla de algo que teine que ver con texto como lo son las otras props y despues si nunca cambiamos la propiedad display en ningun lado porque tenemos que setar lo que es el valor por default 

en realidad es esto necesario ?

2023-10-09 15:03 UTC, Freihart512 commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.scss
>              display: block;
Mmm, estoy seguro de haber puesto este comenatrio en otro lado pero no logro verlo pero en fin 

me hace ruido el `display: block`

de entrada porque error text me habla de algo que teine que ver con texto como lo son las otras props y despues si nunca cambiamos la propiedad display en ningun lado porque tenemos que setar lo que es el valor por default 

en realidad es esto necesario ?

2023-10-09 15:03 UTC, Freihart512 commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.scss
>              display: block;
porque tenemos la clase en dos lugares diferentes?

2023-10-09 22:40 UTC, Freihart512 reviewed
me quede con la idea de que se cambiaria todos los colores a HEX, esto es cierto?

2023-10-11 20:49 UTC, Freihart512 commented on BurgerQueen/src/app/shared/components/header/header.component.scss
> +
parace que aqui tienes 2 lineas en blanco al final 🤔

2023-10-12 13:46 UTC, Luandrada commented on BurgerQueen/src/app/shared/components/header/header.component.scss
> +
no, es uan sola . el archivo llega hasta donde se numeran las lineas osea linea 96

2023-10-12 20:28 UTC, merged