modificaciones sugeridas implementadas
Luandrada/DEV006-burger-queen-api-client pull request #24
Opened 2023-10-05 18:32 UTC by Luandrada

- Dejar una linea en blanco al final de cada archivo
- variables publicas en AuthService
- Mostrar todos los errores posibles en Sign in component
- En Header Component eliminar el método setPersonalInfo y dejar su lógica dentro del suscrube que es desde el único lugar donde se lo llama

2023-10-05 22:25 UTC, Freihart512 requested changes

2023-10-05 22:25 UTC, Freihart512 commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.html
> +            <span *ngIf="errorMessage" class="text-rojo-uno">{{errorMessage}}</span>
`texto-rojo-uno`
hay que cambiarlo a ingles  y no me hace tanto sentido el "uno"? que significa hay dos tres cuatro? cual es la diferencia entre ellos 🤔

2023-10-05 22:27 UTC, Freihart512 commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.html
> +            <span *ngIf="errorMessage" class="text-rojo-uno">{{errorMessage}}</span>
supongo que dependera el orden en que este se haga merge porque veo que en el otro PR esta clase ya no existe

2023-10-08 18:32 UTC, Luandrada commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.html
> +            <span *ngIf="errorMessage" class="text-rojo-uno">{{errorMessage}}</span>
exacto , esto lo cambie en tu sugerencia en la otra PR

2023-10-09 14:20 UTC, Freihart512 commented on BurgerQueen/src/app/@core/authentication/sign-in/sign-in.component.html
> +            <span *ngIf="errorMessage" class="text-rojo-uno">{{errorMessage}}</span>
ook, entonces esperemos a hacer merge de aquel para poder conmtinuar con este

2023-10-09 22:41 UTC, Freihart512 reviewed
PR bloqueado hasta que se mergie el de la paleta de colores

2023-10-17 01:31 UTC, Freihart512 commented
Parace que el archivo de interfaces falta la línea al final

2023-10-19 18:59 UTC, merged